### PR TITLE
🚀 Add unicode support to Controller.Type()

### PR DESCRIPTION
**Pull request by yemreak**
Releated on:
https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L596-L613

VfjWoZytTs

> IDE: VS Code Theme: DarkCode Theme

### CODE REVIEW

**Comment by moses-palmer** [comment]
Thank you for your contribution!

Before merging, I will amend this a bit to conform to the library style.

I have a question though: is there a reason that you chose to add a fallback rather than replace the current implementation? It seems like your solution to break the unicode character into surrogates and feed them all to `SendInput` in one go is a general solution that would also work for plain ASCII input?

**Comment by kmgb** [comment]
(3 years later)
@moses-palmer You are correct, breaking into surrogates using utf-16le encoding -- as the boppreh/keyboard library does -- is a general solution for this problem. Currently this bug affects any character above the U+FFFF codepoint, which includes many important math symbols that I could use for my applications.

Would you invite another PR to fix this from me or would you like to amend this PR?

**Comment by moses-palmer** [comment]
I had completely forgotten about this!

I'll amend the PR and merge it shortly.

**Comment by moses-palmer** [comment]
Thank you for your contribution! I have merged this into the *master* branch.

**Pull request closed without merging**
